### ISSUE TITLE
Improve user profile page

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#1]
(From Michael)

Create user profiles that include some simple fields:
1. Name
2. Email
3. I live closest to [theme area]
4. ideas submitted
5. recent activity (comments, ideas, votes)
6. (social media) links

**Comment by cspanring** [comment]
Minimum set that would be good:
- user can edit real name (first and last)
- user can add/edit user-picture (or just point to gravatar for now?)
- user can specify "My Station Area"

**Comment by gerlad** [comment]
I propose we use Idios for user profiles, it can do what Michael has suggested. I was not able to use it before, pror to the upgrade to newer Django and Pinax.

http://oss.eldarion.com/idios/docs/0.1/gettingstarted.html

**Comment by cspanring** [comment]
+1 on that. saw it in the Pinax tree, but wasn't really clear about
what it does...

On Tue, Jun 28, 2011 at 10:14 PM, gerlad
reply@reply.github.com
wrote:

**Comment by cspanring** [comment]
closed by f6a74867f83f0bb5c1e30b8e5bfc6f936e0705b4

**Comment by michaelmessina** [comment]
when I click on my user profile link, I'm getting a 404.

**Comment by cspanring** [comment]
problem with legacy data (your and simcha's account) that no profile was created when you signed up. it works for new users though. I added a profile for both of you manually through the admin interface. should work now.

**Comment by michaelmessina** [comment]
gotcha. fantastic!

**Comment by michaelmessina** [comment]
Not sure where this fits in but when you add an item I can't find the option to delete or edit the item.

**Comment by cspanring** [comment]
Currently not implemented.  Please add a separate ticket for that.
On Jul 11, 2011 10:59 PM, "michaelmessina" <
reply@reply.github.com>
wrote:
