### ISSUE TITLE
search group on flickr

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#12]
...for new photos and update cached photo data, with django-cron or so.

**Comment by michaelmessina** [comment]
Using unique tags to aggregate to a website photo pool for people that do not want to get on Flickr. So for example, they are under "Gilman Square" and there a table with some photos next to the station. On Flickr it's tagged gilmansquare or something more unique and it populates on the website. Users can click on the photo and add an idea? Probably far-fetched but wanted to share anyway...

**Comment by cspanring** [comment]
fixed with 0e772e403916391ae2382f98803af43129aa7bfa: creates the command 'updatefromflickr', which crawls the flickr group for new photos. can be run in a cron-job if necessary. but users should add their media through the share-form anyways.

currently existing photos in the interactive somerville have been added by 0e772e403916391ae2382f98803af43129aa7bfa
