### ISSUE TITLE
improve sharing form

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#15]
currently using default template (uni-form).

add validation where useful. http://docs.jquery.com/Plugins/validation does a fairly well job.

**Comment by gerlad** [comment]
Yes, could use some clean up. I'm not in favor of uni-form, so +1 jquery validation.

**Comment by cspanring** [comment]
functionality is incluced since 34fe6cecddfffd3178980b7b6377fff8bbea163e . what we need is to make the form visually clearer, re-arrange field-structure (uniform templates?) and better wording for help texts.
