### ISSUE TITLE
add better markdown help

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#16]
as lightbox or so, but don't send users who click the link to the gruber docs. there must be something better, like the github markdown help here on the top right for instance.

**Comment by michaelmessina** [comment]
I defer to you but for the average user, we need basics (as you know). Some items people have become accustomed to like auto-linking urls that start with http: or www, auto-embedding YouTube video urls and Flickr urls - I think you have this in your plans already but just wanted to keep the development conversation going!

**Comment by cspanring** [comment]
I'm thinking of letting people know how to make text bold, add a link and a list. that should be good for content. users shouldn't get too creative with styling their text...
