### ISSUE TITLE
add activity streams

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#17]
...to all pages where it makes sense.

must be modular and applicable across project.

"show 10 most recent related items", mix of ideas, photos, videos, articles, meeting notes, etc.

**Comment by michaelmessina** [comment]
Fantastic! If we can add it to user profile activities that could be good too.

**Comment by cspanring** [comment]
I think we have all functionality (finished with 02406400f6d09aedc40bd37a06dd6195733834bd).
