### ISSUE TITLE
add threaded comments

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#20]
to
- Ideas
- Station Areas
- Themes
- Photos
- Videos
  ...

Pinax provides something like that, right?

**Comment by michaelmessina** [comment]
The easier and more places people can comment - the better! It would be great if we could export comment data into a master comment list (.csv) so we can track the total number of comments and comments by users, on each ideas, station areas etc. It doesn't have to be pretty, just reliable. 

I like this comment system by the way. Could we add the ability for users to edit/update their comment and delete it?

**Comment by gerlad** [comment]
There's a bit of disagreement in Pinax circles about which threaded comments package is better. I think the right solution for us with newer Pinax may be django-mptt.

https://github.com/django-mptt/django-mptt.git

I've assigned this one to myself for now.

**Comment by cspanring** [comment]
I'm all for it as long as it's not too complex to implement and actively maintained (which seems to be the case with django-mptt).

I'm going tomorrow to the local Django meetup, maybe I can ask for a few opinions. Meetup topic is doing auth and profiles the right way, which comes in very handy ;-)

**Comment by michaelmessina** [comment]
Hey Gerald, I was wondering if you have any more thoughts on the comment system. I'd be happy to find some examples from the user-side if that's helpful.

**Comment by gerlad** [comment]
Hi Michael, I hope to get some input from our other Michael, Michael Trythall of Lincoln Loop, to assist in the design part of comments. There is some work there now that's not yet exposed; we're using 'mptt_comments' to provide threaded comment capability. 

I've been wrangling with a deadline this Friday but will focus some on comments this week and then much more this weekend and next.

**Comment by michaelmessina** [comment]
Thanks Gerald, looking forward to taking it for a test spin. Any chance we can preview it for our meeting Thursday night (21st)? Or are we still thinking the 25th? Any timeline would be helpful as I'm finishing off my research proposal. Thanks a bunch!

**Comment by cspanring** [comment]
used django's built-in comment system (non-threaded) for a first version. closing it for now (with 8a709ec4ab9f3cf9237c499814d11853491d883b). we need to extend it with threads and provide UI for comment-flags (also built-in) later.

**Comment by michaelmessina** [comment]
Looks good. I like how is appears like a conversation (chat). Adding threaded discussions with reply, edit, delete options are important I think.

**Comment by cspanring** [comment]
I agree; there should be separate tickets/issues for it to be able to prioritize development.
