### ISSUE TITLE
Configure interactivesomerville.org domain

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#21]
add 'CNAME' record for 'hosted.djangozoom.net'

**Comment by cspanring** [comment]
please forward interactivesomerville.org to http://somerville.open-neighborhood.org/ for now.

**Comment by gerlad** [comment]
I need to know what I'm pointing at, i.e. has an ip been assigned for open-neighborhood.org?  That domain l to looks to be 'parked' at the moment, subdomains of it aren't visible yet.  

Will an IP be assigned for somerville.open-neighborhood.org, or should I just point to open-neighborhood.org (once an IP is assigned)? 

I need the IP once it's assigned to complete this request.

thx,
g

**Comment by cspanring** [comment]
I'm not sure if there is an IP... can you just forward the domain to http://somerville.open-neighborhood.org/ ? ....you can do that easily in godaddy's domain manager, there is a "forward" config option...

**Comment by gerlad** [comment]
Sure I can do that. If we plan to transfer the domain it will need to be done again.

**Comment by gerlad** [comment]
this is done.

**Comment by cspanring** [comment]
great, thanks!

I think domain configurations are included in domain transfers...
