### ISSUE TITLE
organize and represent 'participation' items 

### ISSUE THREAD

**Issue by gerlad** [SomervilleCC/interactivesomerville#24]
Currently the participation app contains a model for an Idea. We will need similar models for Photos, Videos, Meeting notes, news articles, ( [#4](https://github.com/SomervilleCC/interactivesomerville/issues/4),  [#5](https://github.com/SomervilleCC/interactivesomerville/issues/5),  [#6](https://github.com/SomervilleCC/interactivesomerville/issues/6), and  [#7](https://github.com/SomervilleCC/interactivesomerville/issues/7)). 

This raises an issue: How to model and present each of these 'items' as part of an activity stream? Previously I'd created separate models for each, and included them as 'shared items' using a generic foreign key reference to each model. Alternatively we can simply include them in a single model, in the participation app. The downside of the 2nd method is it makes a very large single model which can get unruly.

**Comment by cspanring** [comment]
Why not aggregate everything into one large object, order by last modified and paginate from there?

Least common denominator across all models are 'desc', 'author', 'last_modified', 'geometry', 'station', 'theme', 'get_absolute_url' I believe.

To be easier on the DB we can start with selecting that latest 20 objects or so and merging everything before rendering on the page.

**Comment by gerlad** [comment]
A few ways to aggregate: 

a) create an additional model ('items') and using generic foreign keys. Each time a new object i.e. photo, article, etc. is created we signal an 'item' to be created, then pull from this generic table. I did this before with 'shared items' and it worked but seems a bit redundant. 

b) do simple model inheritance: create a base model (containing author, desc, last_modified, geometry), subclass model1 and model2 off of it, do queries using the base model, then switch to the derived type in the page.

c) order each of the models by last_modified or created_date in the view then merge the results into a single list. 

I guess I'm +1 for (c) though it might be worthwhile to do a simple test to see how (b) could work. (a) is industrial strength solution though clunky a bit. that may have changed in django 1.3

**Comment by cspanring** [comment]
(a) sounds good, (b) seems very elegant and (c) is basically quick and
dirty but might work well when we can rely on caching.

my preference would be (b), although I would give the highest priority
to the solution that we can implement the easiest and quickest way to
get the site out the door.

On Wed, Jun 29, 2011 at 10:10 AM, gerlad
reply@reply.github.com
wrote:
