### ISSUE TITLE
Social Links and RSS/Follow

### ISSUE THREAD

**Issue by michaelmessina** [SomervilleCC/interactivesomerville#27]
Add social links to homepage (bottom right above twitter feed should be fine). 

32 x 32 image size should be fine for the social links.

Facebook, Flickr, Twitter, YouTube

RSS feeds? Do we want to create RSS feeds for different streams?
1. Master Feed (all activity)
2. Follow ideas
3. Follow stations
4. Follow comments

**Comment by cspanring** [comment]
are people still using RSS?

**Comment by michaelmessina** [comment]
I think people are clicking "follow" more than anything then they get it via email or a dash (like tumblr or posterous) or it's automated e.g. FB feeds. Not highest priority with everything else on the list but nice feature to enhance user experience and to get people to come back. A master RSS is probably not necessary, except maybe for admins and staff at this point.

**Comment by cspanring** [comment]
links to accounts are not a problem, mainly a design-issue. deeper integration with let's say Facebook I would put off until we pass the first 100 active users or so...

**Comment by michaelmessina** [comment]
Sounds good.

**Comment by cspanring** [comment]
first step is to integrate a "sharethis" button on every item. that's cheap for us and helps viral distribution.

**Comment by michaelmessina** [comment]
Do you want me to set up the account?

Sent from my iPhone

On Aug 4, 2011, at 3:04 PM, cspanring
reply@reply.github.com
wrote:

**Comment by cspanring** [comment]
I think there is an "account-less" option available, but yes, please go ahead and register an account if you think it makes sense.

**Comment by michaelmessina** [comment]
Christian, I set up an account and will send you the login info via email.
