### ISSUE TITLE
add media thumbnails to activity stream

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#29]

**Comment by cspanring** [comment]
closed by ef14c1ca59c71c6cc2130a84df49466d7e075a1b

**Comment by michaelmessina** [comment]
Can we add thumbnails for Flickr photos? When sharing a link, it would be great to have thumbnail options based on the content on the page shared (similar to Facebook). However, I think the Flickr thumbnails are more important.

**Comment by cspanring** [comment]
the application pulls thumbnails from flickr. I saw that you embedded flickr photos in an idea. the problem is, that the application isn't designed for that. in the "media" tab on the form you can paste a flickr, youtube or vimeo url and it will know what it its, grab the thumbnail, the embed code, etc. and show it in the activity streams. just like on facebook ;-)

as far as I remember the requirement was to have different types of items available that users can share, and keep them separated - idea, photo/video, meeting note, data, news article.

the sharing form is not super clear and needs improvement, definitely.
