### ISSUE TITLE
Google Maps default view and drag & drop icon color

### ISSUE THREAD

**Issue by michaelmessina** [SomervilleCC/interactivesomerville#34]
Could we make the "Map" the default view on Google Maps rather than "Simple" - I think the user will find locations quicker.

Also, if possible, I think the drag and drop icon would stand out better against the map if it were green or blue.

**Comment by cspanring** [comment]
you can create custom map icons at http://mapicons.nicolasmollet.com/ , I took all of them from there.

Google's street map is pretty busy and distracts from the overlay, the greenline, so it's a tradeoff and we would need decide what the focus of the map should be.

**Comment by michaelmessina** [comment]
Indeed, good point. I think we want them to share an idea and hopefully drag the icon in the right spot. I just thought the map would help the average user. It might be a good question for our audience to answer.

**Comment by cspanring** [comment]
I wouldn't change the map type on the homepage. on the form and other subpages where identifying location becomes more important it probably makes sense to put the streetmap there.

**Comment by michaelmessina** [comment]
That sounds like a good solution to me. Makes sense for the user and the look and feel. Probably better for load time on the homepage too.
