### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by michaelmessina** [SomervilleCC/interactivesomerville#35]
I'm getting a 404 for the following page: http://interactivesomerville.djangozoom.net/about/ (clicked from home page "learn about this project")

**Comment by cspanring** [comment]
They are just empty placeholders for now (not sure if we have content
for those pages at all). However, I'll add "static pages" for that.

**Comment by michaelmessina** [comment]
Were you waiting for content from Meridith? Let me know if I can help.

**Comment by cspanring** [comment]
fixed with e081117c20e499cd39add600cd5bd16d51ef76b7
