### ISSUE TITLE
add Photo model

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#4]
with some basic functionality.

Initially no upload, specify Flickr URL, grab photo-id, sources and geotags to cache in database.

In the long run we probably want our own photo app (see what's happening to Yahoo services lately?).

If homebrewn photo app with upload, etc. is easy, then go for it. Storage shouldn't be an issue.

**Comment by gerlad** [comment]
A django app/model for Flickr is available in the legacy application, under apps/photos. Like videos it uses 'generics' (i.e. (from django.contrib.contenttypes) as a way of associating a photo as a 'shared' item, and listing it in the 'shared' activity stream.

**Comment by cspanring** [comment]
my quest to make things as simple as possible lead me to [djangoembed](http://readthedocs.org/docs/djangoembed/en/latest/) and I'm thinking of just creating a "media" model for photos and videos, that only holds the media-url and passes all the other tasks off to djangoembed. can you think of a reason why that wouldn't work?

**Comment by cspanring** [comment]
closed by 65e7a19901968eb25b5ede5e5056a2c0cc34d0ff
