### ISSUE TITLE
link to SCC site in footer

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#48]

**Comment by michaelmessina** [comment]
We could probably add social icons w/ links there too?

Sent from my iPhone

On Aug 4, 2011, at 2:59 PM, cspanring
reply@reply.github.com
wrote:

**Comment by cspanring** [comment]
yes. do you know or can you produce a nice greyscale icon set?

**Comment by michaelmessina** [comment]
I'll see if I can locate an icon set, thanks!

Sent from my iPhone

On Aug 4, 2011, at 4:20 PM, cspanring
reply@reply.github.com
wrote:
