### ISSUE TITLE
add Video model

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#5]
with some basic functionality.

YouTube URL, grab video embed code, title and geotags and cache in database.

Is there a python/django YouTube API library?

**Comment by gerlad** [comment]
A django app/model for Youtube is available in the legacy application, under apps/video. It uses 'generics' (i.e. (from django.contrib.contenttypes) as a way of associating a video as a 'shared' item, and listing it in the 'shared' activity stream.

**Comment by cspanring** [comment]
closed by 65e7a19901968eb25b5ede5e5056a2c0cc34d0ff
