### ISSUE TITLE
add Meeting Notes model

### ISSUE THREAD

**Issue by cspanring** [SomervilleCC/interactivesomerville#6]
with some basic functionality.

Allow file upload for .pdf and .doc up to 2MB.

Fields: File, Link (in case PDF is larger or hosted somewhere else), Meeting Date, Description

**Comment by michaelmessina** [comment]
Would this be converted to text on the website, like a new page within /meetingnotes/? Or just links to .pdf and .doc? Would it be primarily on the backend? Good idea either way.

**Comment by cspanring** [comment]
No, it won't be converted to text, it's meant as downloadable resource, provided by users, nothing exclusively on the backend.
